In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfTransformer
from scipy.spatial.distance import cosine

In [2]:
def cosine_similarity(data):
    #given a processed data, compute cosine similarity
    final_sample=data
    transformer = TfidfTransformer()
    df_new=final_sample.values.tolist()
    tfidf_sparse = transformer.fit_transform(df_new)
    matrix_result=tfidf_sparse.todense()
    tf_idf=pd.DataFrame(matrix_result)
    tf_idf.columns=final_sample.columns
    columns=tf_idf.columns
    d={}
    for sample in columns:
        d[sample]=[1-cosine(tf_idf["Ceramic"], tf_idf[sample])]
    similarity=pd.DataFrame.from_dict(d)
    similarity.index=['score']
    similarity.sort_values(by='score', ascending=False, axis=1, inplace=True)
    return similarity

In [3]:
def tf_idf_score(df):
    df_removed_0=df[df["Blank_pipe-APW.raw filtered Peak height"]==0]
    df_new=df_removed_0.drop(["row ID", "row m/z","row retention time"], axis=1)
    final_df=pd.DataFrame()
    for column in df_new.columns:
        final_df[column.split('_')[0]]=df_new[column]
    final_df.drop('Blank',axis=1, inplace=True)
    result=cosine_similarity(final_df)
    return result

# Result of CP1

In [6]:
cp1=pd.read_csv("Blind_Pipes-APW-CP1.csv")

tf_idf_score(cp1).transpose()

                   score
Ceramic         1.000000
Nglauca         0.043655
Ntabacum        0.042324
Nquadrivalvis   0.026963
Nobtusifolia    0.021349
Csericea        0.016470
Nattenuata      0.015881
Linflata        0.014534
AmericanSpirit  0.013823
Rglabra         0.011723
Auvaursi        0.010712
Aludoviciana    0.010492
Nrustica        0.008084
Gshallon        0.004441
Vthapsus        0.003591
Ssonomensis     0.003386
Tbrevifolia     0.002249

# Result of CP2

In [7]:
cp2=pd.read_csv("Blind_Pipes-APW-CP2.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Ntabacum        0.064132
Nglauca         0.043808
Nquadrivalvis   0.029638
Csericea        0.023107
AmericanSpirit  0.022680
Nobtusifolia    0.021521
Nattenuata      0.019481
Linflata        0.014858
Nrustica        0.011211
Auvaursi        0.011089
Aludoviciana    0.007964
Rglabra         0.007686
Ssonomensis     0.005552
Gshallon        0.004874
Vthapsus        0.003996
Tbrevifolia     0.002976

# Result of CP3

In [8]:
cp2=pd.read_csv("Blind_Pipes-APW-CP3.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.050823
Ntabacum        0.042564
AmericanSpirit  0.035727
Nquadrivalvis   0.021634
Csericea        0.017548
Nattenuata      0.015872
Linflata        0.015291
Nobtusifolia    0.013911
Auvaursi        0.013661
Rglabra         0.009738
Aludoviciana    0.009419
Nrustica        0.008117
Gshallon        0.007043
Vthapsus        0.005089
Ssonomensis     0.003790
Tbrevifolia     0.002113

# Result of CP4

In [9]:
cp2=pd.read_csv("Blind_Pipes-APW-CP4.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.049114
Ntabacum        0.048789
Nquadrivalvis   0.033609
Nattenuata      0.026263
Nobtusifolia    0.026204
Csericea        0.023632
AmericanSpirit  0.021448
Linflata        0.016542
Nrustica        0.015339
Auvaursi        0.011156
Aludoviciana    0.007824
Rglabra         0.006332
Gshallon        0.005346
Vthapsus        0.004324
Ssonomensis     0.004184
Tbrevifolia     0.003688

## Results of CP5

In [10]:
cp2=pd.read_csv("Blind_Pipes-APW-CP5.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.077337
Ntabacum        0.053119
AmericanSpirit  0.043979
Nobtusifolia    0.041877
Nquadrivalvis   0.038842
Nrustica        0.026166
Csericea        0.024242
Nattenuata      0.021553
Aludoviciana    0.018262
Rglabra         0.017214
Linflata        0.015038
Gshallon        0.013844
Auvaursi        0.012387
Vthapsus        0.005971
Ssonomensis     0.005668
Tbrevifolia     0.004307

## Results of CP6

In [12]:
cp2=pd.read_csv("Blind_Pipes-APW-CP6.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.068978
Ntabacum        0.055773
AmericanSpirit  0.031718
Linflata        0.030995
Nquadrivalvis   0.027831
Gshallon        0.026983
Csericea        0.026957
Nobtusifolia    0.026496
Rglabra         0.023794
Nrustica        0.020392
Vthapsus        0.018202
Auvaursi        0.018080
Nattenuata      0.017976
Aludoviciana    0.016799
Ssonomensis     0.012074
Tbrevifolia     0.009740

## Results of CP7

In [13]:
cp2=pd.read_csv("Blind_Pipes-APW-CP7.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Ntabacum        0.035783
Nglauca         0.024417
Nattenuata      0.021448
AmericanSpirit  0.019018
Csericea        0.015020
Auvaursi        0.011363
Nquadrivalvis   0.010452
Nrustica        0.009898
Linflata        0.008755
Nobtusifolia    0.006698
Rglabra         0.005404
Aludoviciana    0.003193
Vthapsus        0.002607
Gshallon        0.002307
Ssonomensis     0.001851
Tbrevifolia     0.001567

## Results of CP8

In [14]:
cp2=pd.read_csv("Blind_Pipes-APW-CP8.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Csericea        0.095916
Ntabacum        0.052381
Nglauca         0.044872
AmericanSpirit  0.029586
Auvaursi        0.024908
Nquadrivalvis   0.019135
Nattenuata      0.014780
Linflata        0.013278
Gshallon        0.013074
Nobtusifolia    0.012908
Rglabra         0.012645
Nrustica        0.010269
Vthapsus        0.007865
Aludoviciana    0.006659
Tbrevifolia     0.006549
Ssonomensis     0.006282

## Results of CP9

In [15]:
cp2=pd.read_csv("Blind_Pipes-APW-CP9.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nattenuata      0.031505
Nglauca         0.024427
Ntabacum        0.022697
AmericanSpirit  0.020187
Nquadrivalvis   0.015207
Auvaursi        0.011832
Nobtusifolia    0.010497
Nrustica        0.010062
Linflata        0.009436
Csericea        0.009088
Rglabra         0.003938
Gshallon        0.003290
Ssonomensis     0.003261
Aludoviciana    0.002274
Vthapsus        0.001990
Tbrevifolia     0.001101

## Results of CP10

In [16]:
cp2=pd.read_csv("Blind_Pipes-APW-CP10.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Ntabacum        0.037005
Nglauca         0.028750
Nattenuata      0.023239
AmericanSpirit  0.018574
Nobtusifolia    0.017015
Auvaursi        0.013231
Nquadrivalvis   0.012854
Csericea        0.009246
Nrustica        0.008120
Aludoviciana    0.006605
Vthapsus        0.005844
Linflata        0.005655
Ssonomensis     0.004039
Gshallon        0.003740
Rglabra         0.002862
Tbrevifolia     0.000975

## Results of CP11

In [17]:
cp2=pd.read_csv("Blind_Pipes-APW-CP11.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nquadrivalvis   0.110675
Nattenuata      0.098576
Nglauca         0.061273
Ntabacum        0.059967
Nrustica        0.034808
Nobtusifolia    0.029699
Aludoviciana    0.019037
AmericanSpirit  0.012315
Linflata        0.010838
Auvaursi        0.010623
Vthapsus        0.009315
Csericea        0.009236
Gshallon        0.006735
Ssonomensis     0.005671
Tbrevifolia     0.003452
Rglabra         0.003310

## Results of CP12

In [18]:
cp2=pd.read_csv("Blind_Pipes-APW-CP12.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nobtusifolia    0.114528
Nglauca         0.101750
Nattenuata      0.081593
Nrustica        0.072407
Ntabacum        0.069169
Nquadrivalvis   0.066273
Aludoviciana    0.051517
Linflata        0.027055
Vthapsus        0.025082
AmericanSpirit  0.022019
Auvaursi        0.019531
Gshallon        0.018178
Ssonomensis     0.014832
Csericea        0.013405
Rglabra         0.009155
Tbrevifolia     0.005455

## Results of CP13

In [19]:
cp2=pd.read_csv("Blind_Pipes-APW-CP13.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Ntabacum        0.093470
Nglauca         0.068241
Nattenuata      0.068212
Nobtusifolia    0.049167
Aludoviciana    0.039393
Nquadrivalvis   0.038366
Nrustica        0.037734
Vthapsus        0.023071
Linflata        0.022431
AmericanSpirit  0.018866
Csericea        0.015589
Auvaursi        0.014846
Rglabra         0.013127
Gshallon        0.011151
Ssonomensis     0.007903
Tbrevifolia     0.003940

## Results of CP14

In [20]:
cp2=pd.read_csv("Blind_Pipes-APW-CP14.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.088483
Nattenuata      0.046636
Ntabacum        0.035009
Nobtusifolia    0.027262
Nquadrivalvis   0.025143
Nrustica        0.017086
Aludoviciana    0.013966
AmericanSpirit  0.011043
Linflata        0.009895
Csericea        0.009207
Vthapsus        0.004626
Auvaursi        0.004150
Ssonomensis     0.002927
Tbrevifolia     0.002867
Gshallon        0.002221
Rglabra         0.002126

## Results of CP15

In [21]:
cp2=pd.read_csv("Blind_Pipes-APW-CP15.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.065418
Nobtusifolia    0.053692
Nattenuata      0.049209
Ntabacum        0.045061
Nrustica        0.044793
Aludoviciana    0.034430
Nquadrivalvis   0.030205
Linflata        0.024708
Csericea        0.018266
Vthapsus        0.017887
AmericanSpirit  0.014039
Ssonomensis     0.011002
Gshallon        0.010656
Tbrevifolia     0.007153
Rglabra         0.006970
Auvaursi        0.006006

## Results of CP16

In [23]:
cp2=pd.read_csv("Blind_Pipes-APW-CP16.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.084435
Ntabacum        0.065927
Nattenuata      0.059120
Nobtusifolia    0.052638
Linflata        0.049797
Nrustica        0.042586
Aludoviciana    0.038709
Nquadrivalvis   0.034311
Vthapsus        0.028731
Auvaursi        0.017833
AmericanSpirit  0.017004
Gshallon        0.014618
Ssonomensis     0.013709
Csericea        0.013444
Rglabra         0.011646
Tbrevifolia     0.004981

## Results of CP17

In [24]:
cp2=pd.read_csv("Blind_Pipes-APW-CP17.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Auvaursi        0.073507
Csericea        0.069728
Gshallon        0.034651
Ntabacum        0.034453
Rglabra         0.024664
Nglauca         0.022478
Nattenuata      0.015831
AmericanSpirit  0.014974
Nrustica        0.012327
Linflata        0.011695
Nquadrivalvis   0.011136
Nobtusifolia    0.008897
Tbrevifolia     0.008101
Vthapsus        0.007464
Ssonomensis     0.007105
Aludoviciana    0.004230

## Results of CP18

In [25]:
cp2=pd.read_csv("Blind_Pipes-APW-CP18.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Csericea        0.081362
Auvaursi        0.061783
Ntabacum        0.049887
Nglauca         0.042277
AmericanSpirit  0.039986
Nattenuata      0.030455
Gshallon        0.027229
Rglabra         0.025623
Linflata        0.022827
Nquadrivalvis   0.016552
Nobtusifolia    0.015658
Nrustica        0.013123
Vthapsus        0.011806
Ssonomensis     0.010509
Aludoviciana    0.009682
Tbrevifolia     0.009561