In [6]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfTransformer
from scipy.spatial.distance import cosine

In [17]:
def cosine_similarity(data):
    #given a processed data, compute cosine similarity
    final_sample=data
    
    #transform the data to tf-idf matrix
    transformer = TfidfTransformer()
    df_new=final_sample.values.tolist()
    tfidf_sparse = transformer.fit_transform(df_new)
    matrix_result=tfidf_sparse.todense()
    tf_idf=pd.DataFrame(matrix_result)
    
    #name the columns
    tf_idf.columns=final_sample.columns
    columns=tf_idf.columns
    d={}
    for sample in columns:
        d[sample]=[1-cosine(tf_idf["Ceramic"], tf_idf[sample])]
    similarity=pd.DataFrame.from_dict(d)
    similarity.index=['score']
    similarity.sort_values(by='score', ascending=False, axis=1, inplace=True)
    return similarity

In [18]:
def tf_idf_score(df):
    #return the tf_idf_score 
    df_removed_0=df[df["Blank_pipe-APW.raw filtered Peak height"]==0]
    df_new=df_removed_0.drop(["row ID", "row m/z","row retention time"], axis=1)
    final_df=pd.DataFrame()
    for column in df_new.columns:
        final_df[column.split('_')[0]]=df_new[column]
    final_df.drop('Blank',axis=1, inplace=True)
    result=cosine_similarity(final_df)
    return result

# Result of CP1

In [9]:
cp1=pd.read_csv("Blind_Pipes-APW-CP1.csv")

tf_idf_score(cp1).transpose()

                   score
Ceramic         1.000000
Ntabacum        0.037005
Nglauca         0.028750
Nattenuata      0.023239
AmericanSpirit  0.018574
Nobtusifolia    0.017015
Auvaursi        0.013231
Nquadrivalvis   0.012854
Csericea        0.009246
Nrustica        0.008120
Aludoviciana    0.006605
Vthapsus        0.005844
Linflata        0.005655
Ssonomensis     0.004039
Gshallon        0.003740
Rglabra         0.002862
Tbrevifolia     0.000975

# Result of CP2

In [10]:
cp2=pd.read_csv("Blind_Pipes-APW-CP2.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nquadrivalvis   0.110675
Nattenuata      0.098576
Nglauca         0.061273
Ntabacum        0.059967
Nrustica        0.034808
Nobtusifolia    0.029699
Aludoviciana    0.019037
AmericanSpirit  0.012315
Linflata        0.010838
Auvaursi        0.010623
Vthapsus        0.009315
Csericea        0.009236
Gshallon        0.006735
Ssonomensis     0.005671
Tbrevifolia     0.003452
Rglabra         0.003310

# Result of CP3

In [11]:
cp2=pd.read_csv("Blind_Pipes-APW-CP3.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nobtusifolia    0.114528
Nglauca         0.101750
Nattenuata      0.081593
Nrustica        0.072407
Ntabacum        0.069169
Nquadrivalvis   0.066273
Aludoviciana    0.051517
Linflata        0.027055
Vthapsus        0.025082
AmericanSpirit  0.022019
Auvaursi        0.019531
Gshallon        0.018178
Ssonomensis     0.014832
Csericea        0.013405
Rglabra         0.009155
Tbrevifolia     0.005455

# Result of CP4

In [12]:
cp2=pd.read_csv("Blind_Pipes-APW-CP4.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Ntabacum        0.093470
Nglauca         0.068241
Nattenuata      0.068212
Nobtusifolia    0.049167
Aludoviciana    0.039393
Nquadrivalvis   0.038366
Nrustica        0.037734
Vthapsus        0.023071
Linflata        0.022431
AmericanSpirit  0.018866
Csericea        0.015589
Auvaursi        0.014846
Rglabra         0.013127
Gshallon        0.011151
Ssonomensis     0.007903
Tbrevifolia     0.003940

## Results of CP5

In [13]:
cp2=pd.read_csv("Blind_Pipes-APW-CP5.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.088483
Nattenuata      0.046636
Ntabacum        0.035009
Nobtusifolia    0.027262
Nquadrivalvis   0.025143
Nrustica        0.017086
Aludoviciana    0.013966
AmericanSpirit  0.011043
Linflata        0.009895
Csericea        0.009207
Vthapsus        0.004626
Auvaursi        0.004150
Ssonomensis     0.002927
Tbrevifolia     0.002867
Gshallon        0.002221
Rglabra         0.002126

## Results of CP6

In [14]:
cp2=pd.read_csv("Blind_Pipes-APW-CP6.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.084435
Ntabacum        0.065927
Nattenuata      0.059120
Nobtusifolia    0.052638
Linflata        0.049797
Nrustica        0.042586
Aludoviciana    0.038709
Nquadrivalvis   0.034311
Vthapsus        0.028731
Auvaursi        0.017833
AmericanSpirit  0.017004
Gshallon        0.014618
Ssonomensis     0.013709
Csericea        0.013444
Rglabra         0.011646
Tbrevifolia     0.004981

## Results of CP7

In [15]:
cp2=pd.read_csv("Blind_Pipes-APW-CP7.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Auvaursi        0.073507
Csericea        0.069728
Gshallon        0.034651
Ntabacum        0.034453
Rglabra         0.024664
Nglauca         0.022478
Nattenuata      0.015831
AmericanSpirit  0.014974
Nrustica        0.012327
Linflata        0.011695
Nquadrivalvis   0.011136
Nobtusifolia    0.008897
Tbrevifolia     0.008101
Vthapsus        0.007464
Ssonomensis     0.007105
Aludoviciana    0.004230

## Results of CP8

In [16]:
cp2=pd.read_csv("Blind_Pipes-APW-CP8.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Csericea        0.081362
Auvaursi        0.061783
Ntabacum        0.049887
Nglauca         0.042277
AmericanSpirit  0.039986
Nattenuata      0.030455
Gshallon        0.027229
Rglabra         0.025623
Linflata        0.022827
Nquadrivalvis   0.016552
Nobtusifolia    0.015658
Nrustica        0.013123
Vthapsus        0.011806
Ssonomensis     0.010509
Aludoviciana    0.009682
Tbrevifolia     0.009561