In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfTransformer
from scipy.spatial.distance import cosine

In [2]:
def cosine_similarity(data):
    #given a processed data, compute cosine similarity
    final_sample=data
    transformer = TfidfTransformer(sublinear_tf = "True")
    df_new=final_sample.values.tolist()
    tfidf_sparse = transformer.fit_transform(df_new)
    matrix_result=tfidf_sparse.todense()
    tf_idf=pd.DataFrame(matrix_result)
    tf_idf.columns=final_sample.columns
    columns=tf_idf.columns
    d={}
    for sample in columns:
        d[sample]=[1-cosine(tf_idf["Ceramic"], tf_idf[sample])]
    similarity=pd.DataFrame.from_dict(d)
    similarity.index=['score']
    similarity.sort_values(by='score', ascending=False, axis=1, inplace=True)
    return similarity

In [3]:
def tf_idf_score(df):
    df_removed_0=df[df["Blank_pipe-APW.raw filtered Peak height"]==0]
    df_new=df_removed_0.drop(["row ID", "row m/z","row retention time"], axis=1)
    final_df=pd.DataFrame()
    for column in df_new.columns:
        final_df[column.split('_')[0]]=df_new[column]
    final_df.drop('Blank',axis=1, inplace=True)
    result=cosine_similarity(final_df)
    return result

# Result of CP1

In [4]:
cp1=pd.read_csv("Blind_Pipes-APW-CP1.csv")

tf_idf_score(cp1).transpose()

                   score
Ceramic         1.000000
Nglauca         0.045149
Ntabacum        0.041916
Nquadrivalvis   0.030542
Nobtusifolia    0.022906
Csericea        0.022020
Nattenuata      0.018945
Linflata        0.016533
AmericanSpirit  0.016446
Auvaursi        0.014698
Aludoviciana    0.013553
Nrustica        0.012102
Rglabra         0.011977
Gshallon        0.006689
Ssonomensis     0.005083
Vthapsus        0.004747
Tbrevifolia     0.004269

# Result of CP2

In [5]:
cp2=pd.read_csv("Blind_Pipes-APW-CP2.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Ntabacum        0.065700
Nglauca         0.043307
Nquadrivalvis   0.036318
Csericea        0.030938
AmericanSpirit  0.026195
Nobtusifolia    0.024758
Nattenuata      0.019617
Linflata        0.018320
Nrustica        0.013670
Auvaursi        0.011816
Aludoviciana    0.010082
Rglabra         0.008137
Gshallon        0.006261
Ssonomensis     0.006017
Vthapsus        0.005063
Tbrevifolia     0.004282

# Result of CP3

In [6]:
cp2=pd.read_csv("Blind_Pipes-APW-CP3.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.050439
Ntabacum        0.046155
AmericanSpirit  0.036754
Nquadrivalvis   0.027398
Csericea        0.021193
Nobtusifolia    0.016036
Nattenuata      0.015962
Linflata        0.015819
Auvaursi        0.014048
Nrustica        0.010630
Aludoviciana    0.010494
Rglabra         0.010099
Gshallon        0.008103
Vthapsus        0.005699
Ssonomensis     0.004312
Tbrevifolia     0.002974

# Result of CP4

In [7]:
cp2=pd.read_csv("Blind_Pipes-APW-CP4.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Ntabacum        0.058822
Nglauca         0.047932
Nquadrivalvis   0.043378
Nobtusifolia    0.029481
Csericea        0.026665
Nattenuata      0.026586
AmericanSpirit  0.025286
Linflata        0.019255
Nrustica        0.017561
Auvaursi        0.012101
Aludoviciana    0.010740
Rglabra         0.007126
Gshallon        0.007027
Vthapsus        0.005622
Tbrevifolia     0.005506
Ssonomensis     0.005246

## Results of CP5

In [8]:
cp2=pd.read_csv("Blind_Pipes-APW-CP5.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.096441
Ntabacum        0.067530
Nquadrivalvis   0.058686
Nobtusifolia    0.055526
AmericanSpirit  0.054448
Csericea        0.038734
Nrustica        0.035210
Nattenuata      0.030964
Aludoviciana    0.029542
Linflata        0.024436
Rglabra         0.021086
Gshallon        0.019988
Auvaursi        0.017856
Vthapsus        0.008922
Ssonomensis     0.008904
Tbrevifolia     0.008416

## Results of CP6

In [9]:
cp2=pd.read_csv("Blind_Pipes-APW-CP6.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.101287
Ntabacum        0.097667
Csericea        0.060937
Linflata        0.058175
Nquadrivalvis   0.056221
AmericanSpirit  0.054523
Nobtusifolia    0.044168
Nrustica        0.040648
Gshallon        0.038902
Nattenuata      0.037420
Aludoviciana    0.033343
Rglabra         0.031402
Auvaursi        0.029015
Vthapsus        0.028379
Ssonomensis     0.020405
Tbrevifolia     0.017134

## Results of CP7

In [10]:
cp2=pd.read_csv("Blind_Pipes-APW-CP7.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Ntabacum        0.041454
Nglauca         0.026219
Nattenuata      0.023824
Csericea        0.021369
AmericanSpirit  0.019957
Nquadrivalvis   0.017680
Nrustica        0.012525
Auvaursi        0.010953
Linflata        0.010270
Nobtusifolia    0.008369
Rglabra         0.005301
Aludoviciana    0.004432
Vthapsus        0.003081
Ssonomensis     0.002999
Tbrevifolia     0.002837
Gshallon        0.002802

## Results of CP8

In [11]:
cp2=pd.read_csv("Blind_Pipes-APW-CP8.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Csericea        0.114655
Ntabacum        0.061357
Nglauca         0.056493
AmericanSpirit  0.034019
Auvaursi        0.030451
Nquadrivalvis   0.029228
Nattenuata      0.024170
Nobtusifolia    0.018771
Linflata        0.018428
Gshallon        0.017598
Nrustica        0.017380
Rglabra         0.017014
Aludoviciana    0.013867
Tbrevifolia     0.011161
Vthapsus        0.010648
Ssonomensis     0.009352

## Results of CP9

In [12]:
cp2=pd.read_csv("Blind_Pipes-APW-CP9.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.032999
Nattenuata      0.032447
Ntabacum        0.031493
AmericanSpirit  0.022709
Nquadrivalvis   0.022328
Csericea        0.014800
Nrustica        0.014071
Nobtusifolia    0.013095
Auvaursi        0.012167
Linflata        0.011151
Rglabra         0.004647
Ssonomensis     0.004539
Gshallon        0.004431
Aludoviciana    0.004235
Tbrevifolia     0.002721
Vthapsus        0.002384

## Results of CP10

In [13]:
cp2=pd.read_csv("Blind_Pipes-APW-CP10.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Ntabacum        0.053626
Nglauca         0.046741
Nattenuata      0.034630
Nobtusifolia    0.027579
AmericanSpirit  0.026545
Nquadrivalvis   0.022833
Csericea        0.020983
Auvaursi        0.016886
Aludoviciana    0.014191
Nrustica        0.013991
Linflata        0.011384
Vthapsus        0.010665
Gshallon        0.009614
Ssonomensis     0.006761
Rglabra         0.006122
Tbrevifolia     0.005516

## Results of CP11

In [14]:
cp2=pd.read_csv("Blind_Pipes-APW-CP11.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nquadrivalvis   0.140525
Nattenuata      0.117052
Nglauca         0.096985
Ntabacum        0.079867
Nobtusifolia    0.046004
Nrustica        0.045975
Aludoviciana    0.029121
Linflata        0.025761
AmericanSpirit  0.025295
Csericea        0.021029
Vthapsus        0.014635
Auvaursi        0.014246
Gshallon        0.011691
Ssonomensis     0.010084
Tbrevifolia     0.008724
Rglabra         0.007591

## Results of CP12

In [15]:
cp2=pd.read_csv("Blind_Pipes-APW-CP12.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.148778
Nobtusifolia    0.142489
Nattenuata      0.103209
Nrustica        0.096998
Ntabacum        0.095826
Nquadrivalvis   0.092303
Aludoviciana    0.065873
Linflata        0.045840
AmericanSpirit  0.037613
Vthapsus        0.030730
Csericea        0.030361
Auvaursi        0.026791
Gshallon        0.025502
Ssonomensis     0.022876
Rglabra         0.014401
Tbrevifolia     0.011983

## Results of CP13

In [16]:
cp2=pd.read_csv("Blind_Pipes-APW-CP13.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Ntabacum        0.133440
Nglauca         0.129727
Nattenuata      0.094619
Nobtusifolia    0.072269
Nquadrivalvis   0.072013
Nrustica        0.064356
Aludoviciana    0.051556
Linflata        0.043743
AmericanSpirit  0.041558
Csericea        0.039910
Vthapsus        0.028024
Auvaursi        0.024600
Gshallon        0.022768
Rglabra         0.021339
Ssonomensis     0.014785
Tbrevifolia     0.012226

## Results of CP14

In [17]:
cp2=pd.read_csv("Blind_Pipes-APW-CP14.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.111098
Nattenuata      0.057159
Ntabacum        0.051922
Nquadrivalvis   0.040969
Nobtusifolia    0.038423
Nrustica        0.025157
Aludoviciana    0.022916
Linflata        0.019622
Csericea        0.016571
AmericanSpirit  0.016344
Vthapsus        0.008297
Auvaursi        0.007994
Tbrevifolia     0.006703
Gshallon        0.006238
Ssonomensis     0.005525
Rglabra         0.005483

## Results of CP15

In [18]:
cp2=pd.read_csv("Blind_Pipes-APW-CP15.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.103463
Nobtusifolia    0.070353
Ntabacum        0.068947
Nattenuata      0.065950
Nrustica        0.058968
Nquadrivalvis   0.048692
Aludoviciana    0.042782
Linflata        0.041728
Csericea        0.033866
AmericanSpirit  0.026189
Vthapsus        0.021646
Gshallon        0.020041
Ssonomensis     0.016354
Tbrevifolia     0.013267
Auvaursi        0.013003
Rglabra         0.011429

## Results of CP16

In [19]:
cp2=pd.read_csv("Blind_Pipes-APW-CP16.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Nglauca         0.143467
Ntabacum        0.089332
Linflata        0.083128
Nobtusifolia    0.077371
Nattenuata      0.076873
Nrustica        0.061453
Nquadrivalvis   0.057782
Aludoviciana    0.052420
AmericanSpirit  0.035437
Vthapsus        0.033920
Csericea        0.033283
Auvaursi        0.025818
Gshallon        0.024789
Ssonomensis     0.020869
Rglabra         0.017364
Tbrevifolia     0.013998

## Results of CP17

In [20]:
cp2=pd.read_csv("Blind_Pipes-APW-CP17.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Csericea        0.109717
Auvaursi        0.109664
Ntabacum        0.057572
Gshallon        0.051239
Nglauca         0.044573
Rglabra         0.037924
AmericanSpirit  0.029739
Nquadrivalvis   0.028325
Nattenuata      0.026934
Linflata        0.022980
Nrustica        0.020403
Nobtusifolia    0.019420
Tbrevifolia     0.016874
Vthapsus        0.013490
Aludoviciana    0.012070
Ssonomensis     0.012043

## Results of CP18

In [21]:
cp2=pd.read_csv("Blind_Pipes-APW-CP18.csv")
tf_idf_score(cp2).transpose()

                   score
Ceramic         1.000000
Csericea        0.131745
Auvaursi        0.095906
Ntabacum        0.078457
Nglauca         0.072284
AmericanSpirit  0.056841
Nattenuata      0.044994
Gshallon        0.042155
Nquadrivalvis   0.039070
Rglabra         0.038142
Linflata        0.036471
Nobtusifolia    0.032205
Nrustica        0.023971
Aludoviciana    0.020409
Vthapsus        0.018053
Ssonomensis     0.017465
Tbrevifolia     0.017111